name: Deploy VuePress site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Fix vuepress execute permission
        run: chmod +x ./node_modules/.bin/vuepress

      - name: Build VuePress site
        run: npm run docs:build

      # 如果没有自定义域名，可以删掉这个步骤
      - name: Add CNAME for custom domain
        run: echo "docs.example.com" > docs/.vuepress/dist/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
          publish_branch: gh-pages  # 自动创建 gh-pages 分支
          force_orphan: true        # 确保分支干净

      - name: Show GitHub Pages URL
        run: echo "https://chenximoon.github.io/DailyNotesCode/"
